service: play-graphql

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1


functions:
  api:
    handler: handler.graphql
    events:
    - http:
        path: graphql
        method: post
        # cors: true
        integration: lambda-proxy
